### ISSUE TITLE
Moving template to another folder - empty folder is gone until restart

### ISSUE THREAD

**Issue by DanSman** [dragotin/kraft#106] opened 2021-04-10 21:21 UTC
Hi

Actually, the title already describes it.

Edit:
I think there are more problems.
The entire folder becomes unusable when you move templates

Edit 2:
Maybe a sync button helps ;)

**Comment by dragotin** [comment] 2021-04-11 11:35
I am not able to reproduce that. Can you describe more in detail? Is that in your setup with a central database? If you start Kraft from a console, do you see any output there that indicates a problem?

**Comment by DanSman** [comment] 2021-04-11 21:01
Create a folder and another folder on top of that. Create two templates in the first folder and move one template to the sec folder.

There is nothing in the console.

**Comment by dragotin** [comment] 2022-01-15 21:14
Thanks for reporting these bugs. I dug deeper and fixed a whole bunch of issues with catalog sorting with the commit mentioned above.
Now, manual sorting of catalogs on the catalog chapter and -item level by moving items around and dropping them on the right place should work fine.

Also, all catalog items that disappeared (because they got assigned an catalog chapter ID of 0 by a bug) will appear again on the top level. That might clutter peoples list a bit, but at least their work is saved.

Again, thanks for the report and the patience.

**Closed by dragotin** 2022-01-15 21:14 UTC
