### ISSUE TITLE
Standard Text Catalog display issue

### ISSUE THREAD

**Issue by SmokeMaster1** [dragotin/kraft#51] opened 2018-10-27 11:36 UTC
(I'm at german translation (its called "Standard Mustertexte") and don't know how its named in english, the mentioned issue is at the first catalog, not the 2nd "Material" Catalog)
I add a verry big standard text to the catalog and it isn't displayed correct after creation. The text is cutted but the entry take the whole window.
Also i'm not able to edit it, after opening the edit window the edit window is too big for the screen and the buttons are no longer visible.

**Comment by dragotin** [comment] 2018-10-31 20:39
Note to self: The text is stored in the the datatype TEXT in both mysql and sqlite. MySQL has a limit of 65kB for text. Sqlite is not limited.
(This is not the reason for this issue, it is just interesting info.)

**Comment by SmokeMaster1** [comment] 2018-11-01 11:08
![screenshot_20181101_115140](https://user-images.githubusercontent.com/13787827/47847989-34e11300-ddcd-11e8-81a9-0ce5fe8d5117.png)
![screenshot_20181101_115452](https://user-images.githubusercontent.com/13787827/47847990-34e11300-ddcd-11e8-9ee1-874635ec6310.png)
![screenshot_20181101_115508](https://user-images.githubusercontent.com/13787827/47847991-3579a980-ddcd-11e8-8420-fc2f72c51b9a.png)

The buttons "OK" and "Cancel" are outside of the visible screen, i have to "grab" the window at the frame to move it until i see the buttons. I think it would be more comfortable if the windows maximum size can be set to maximum monitor resolution. 

If i add more than one of these big entries it's hard to scroll inside the catalog view, its not longer a smooth scrolling... its more a jumping between entrys. (hard to describe) would be more comfortable if the text is cutted to one line. The entry is cutted if i change the size of the column, and a big blank space apears.

**Comment by SmokeMaster1** [comment] 2018-11-01 11:34
My workaround is:
I add a subfolder for every entry that contains a short description in its name.

Maybe a solution without automated cutting can be a separate entry for a header inside the "add new entry window" that is used only inside the catalog view. Inside a document the full text appears.

Long-text and short-text as described [here](https://de.wikipedia.org/wiki/Leistungsverzeichnis) and the short text is used for the overwiev inside the catalouge view.

But this sounds like a lot of work to me because headers or a short-text/long-text isn't implemented inside Kraft now. (Or i didn't see it)

 A problem is that many users already have existing entries without headers (as we dont have headers now). If only headers are visible inside the catalogue view, every existing entry out there is displayed without text after updating. So we also need a automated header creation.

Because of this i think a automated cutting to one line inside the catalog view should be a good solution.

**Comment by dragotin** [comment] 2018-11-01 21:17
The big growing editor window can not be reproduced here with version 0.82. And since I changed things in this window quite a bit from 0.81 -> 0.82 it would be good if you could test that with the latest version again. Maybe it is really not an issue any more.

I will look into a fix for the catalog view, cutting sounds resonable.

**Comment by dragotin** [comment] 2018-12-28 10:42
Fixed with the mentioned commit. It abbreviates long texts in the treeview and also fixes the dialog to edit. Reopen if that is still not good.

**Closed by dragotin** 2018-12-28 10:42 UTC
Labels: bug
